name: Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  lab:
    name: Lab app tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@main
    - name: Get node version
      run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_OUTPUT
      id: nvm
    - name: Install correct node version
      uses: actions/setup-node@v2
      with:
        node-version: ${{ steps.nvm.outputs.NODE_VERSION }}
    - name: Setup pnpm
      uses: pnpm/action-setup@v3.0.0
      with:
          version: 8
    - name: Install Dependencies
      run: pnpm i --frozen-lockfile        
    - name: Cypress.io
      uses: cypress-io/github-action@v6.7.8
      with:
          browser: chrome
          project: ./apps/lab
          build: pnpm build
          start: pnpm start --filter=@1xdev/lab
          wait-on: "http://localhost:3000"
  homepage:
    name: Homepage app tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@main
    - name: Get node version
      run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_OUTPUT
      id: nvm
    - name: Install correct node version
      uses: actions/setup-node@v2
      with:
        node-version: ${{ steps.nvm.outputs.NODE_VERSION }}
    - name: Setup pnpm
      uses: pnpm/action-setup@v3.0.0
      with:
          version: 8
    - name: Install Dependencies
      run: pnpm i --frozen-lockfile             
    - name: Cypress.io
      uses: cypress-io/github-action@v6.7.8
      with:
          browser: chrome
          project: ./apps/homepage
          build: pnpm build
          start: pnpm start --filter=@1xdev/homepage
          wait-on: "http://localhost:3000"
          
