name: PR Title

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - labeled
      - unlabeled
jobs:
  title:
    name: Checker
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@main
    - name: Get node version
      run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_OUTPUT
      id: nvm
    - name: Install correct node version
      uses: actions/setup-node@v2
      with:
        node-version: ${{ steps.nvm.outputs.NODE_VERSION }}
    - name: Setup pnpm
      uses: pnpm/action-setup@v3.0.0
      with:
          version: 8
    - name: Install Dependencies
      run: pnpm i
    - name: PR Title Checker              
      uses: thehanimo/pr-title-checker@v1.4.3
      with:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  