name: Publish

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Publish packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: "0"
          token: ${{ secrets.GH_TOKEN }}

      - name: Set up github user
        run: |
          git config --global user.name "@inavac182"
          git config --global user.email "16787893+inavac182@users.noreply.github.com"

      - name: Setup pnpm 9
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Get node version
        run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_OUTPUT
        id: nvm

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.nvm.outputs.NODE_VERSION }}
          registry-url: 'https://registry.npmjs.org'
          scope: 1xdev
          always-auth: true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Install Dependencies
        run: pnpm i

      - name: Build packages
        run: pnpm build

      - name: Publish to npm
        run: pnpm publish:packages
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
