name: Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@main
    - name: Get node version
      run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_OUTPUT
      id: nvm
    - name: Install correct node version
      uses: actions/setup-node@v2
      with:
        node-version: ${{ steps.nvm.outputs.NODE_VERSION }}
    - name: Setup pnpm
      uses: pnpm/action-setup@v3.0.0
      with:
          version: 8
    - name: Install Dependencies
      run: pnpm i
    - name: Test
      run: pnpm test
  lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@main
    - name: Get node version
      run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_OUTPUT
      id: nvm
    - name: Install correct node version
      uses: actions/setup-node@v2
      with:
        node-version: ${{ steps.nvm.outputs.NODE_VERSION }}
    - name: Setup pnpm
      uses: pnpm/action-setup@v3.0.0
      with:
          version: 8
    - name: Install Dependencies
      run: pnpm i
    - name: Lint
      run: pnpm lint
